# Generated by Django 4.1.3 on 2024-09-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeoffapi', '0002_trip_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpass',
            name='traveler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='takeoffapi.traveler'),
        ),
        migrations.AddField(
            model_name='boardingpass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='takeoffapi.user'),
        ),
    ]
