# Generated by Django 4.1.3 on 2024-09-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeoffapi', '0003_boardingpass_traveler_boardingpass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingpass',
            name='traveler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='takeoffapi.traveler'),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='takeoffapi.user'),
        ),
    ]
